spring:
  datasource:
    url: ${DB_URL:jdbc:h2:mem:test}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
    driverClassName: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        default_batch_fetch_size: 100
        globally_quoted_identifiers: true
    open-in-view: false

  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

naver:
  api:
    url: ${NAVER_API_URL:https://test.com}
    referer: ${NAVER_API_REFERER:https://test.com}
    query: ${NAVER_API_QUERY:}
